### ISSUE TITLE
Add flag to change working directory

### ISSUE THREAD

**Issue by craig-willis** [cropsinsilico/cis_interface#34]
`cisrun` uses the parent directory of the model yaml file as the current working directory for execution.  For the cis-ui execution framework, we want to be able to specify the working directory (ideally the cwd where cisrun is executed).    This will allow us to execute relative to the `CIS_WORKSPACE` directory where model code is checked out, but have the model yaml and outputs written to a run directory.

**Comment by langmm** [comment]
@craig-willis I wanted to double check what you meant here because I can convince myself of reading this two ways. Do you need to specify the directory where the models are executed from or do you need to specify the root directory used when interpreting the relative paths in the model yamls? If it's the later would you need to specify a separate root directory for each model? The yaml directory is used for completing relative paths within the yaml and I would think the models will probably not all be checked out in the same directory, but I could be wrong.

**Comment by craig-willis** [comment]
Good question and probably worth discussing further, since we've made a few assumptions and have open questions about our current approach.

The cis-ui generates a single all-encompassing yaml file for the user's defined graph per execution. We've been discussing whether it makes more sense to have a single copy of each model repo at the "CIS_WORKSPACE" level (perhaps via a repo with submodules) or to clone each model repo per run.   For example:

Option 1, single top-level repo with all models, input, output. Per-run directory with graph.yml. The output is left in the model directory because this is where we expect the visualization notebooks to live
```
CIS_WORKSPACE
  cis-models
     @GrCM
         Input
         Output
     @MeM
         Input
         Output
  run1
     graph.yml
```

Option 2: Each run contains a clone of the model repo with input and output
```
CIS_WORKSPACE
    run1
      graph.yml
      model1
        Input
        Output
      model2 
        Input
        Output
```

Either way, we will call `cisrun` with a single yaml and would like to control the execution `cwd`, assuming the yaml file has relative paths for the source, input and output.

**Comment by craig-willis** [comment]
Closing this per our discussion. We no longer need this change.
